name: Run e2e test

on: push

jobs:
  build:

    strategy:
      matrix:
        embulk_version:
          - 0.11.0
        config:
          - e2e/site-explorer/backlink_stats_to_stdout.yml
#          - e2e/site-explorer/domain_rating_to_stdout.yml
#          - e2e/site-explorer/metrics_to_stdout.yml
#          - e2e/site-explorer/ref_domains_history_to_stdout.yml
#          - e2e/keyword_explorer/overview_to_stdout.yml

    runs-on: ubuntu-latest

    env:
      JRUBY_VERSION: 9.4.3.0

    services:
      prism:
        image: ghcr.io/guchey/prism:latest
        ports:
          - 4010:4010

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: "zulu"

      - name: Set up jruby
        run: curl -o /home/runner/jruby-complete-${JRUBY_VERSION}.jar -L https://repo1.maven.org/maven2/org/jruby/jruby-complete/${JRUBY_VERSION}/jruby-complete-${JRUBY_VERSION}.jar

      - name: Set up embulk
        run: |
          curl -o ./embulk -L https://github.com/embulk/embulk/releases/download/v${{ matrix.embulk_version }}/embulk-${{ matrix.embulk_version }}.jar
          chmod +x ./embulk

      - uses: actions/cache@v2
        id: gradle-cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'settings.gradle.kts', 'build.gradle.kts', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

#      - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get -Dartifact=io.github.guchey.embulk.input.ahrefs:embulk-input-ahrefs:0.1.0

      - run: ./gradlew dependencies
        if: steps.gradle-cache.outputs.cache-hit != 'true'

      - run: ./gradlew publishEmbulkPluginMavenPublicationToMavenLocal

      - run: cp build/publications/embulkPluginMaven/pom-default.xml pom.xml

      - uses: actions/cache@v2
        id: m2-cache
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - run: mvn install
        if: steps.m2-cache.outputs.cache-hit != 'true'

      - run: ./gradlew generateEmbulkProperties

      - name: Setup Gem
        run: |
          ./embulk -X jruby=file:///home/runner/jruby-complete-${JRUBY_VERSION}.jar gem install embulk -v ${{ matrix.embulk_version }}
          ./embulk -X jruby=file:///home/runner/jruby-complete-${JRUBY_VERSION}.jar gem install msgpack

      - name: display embulk.properties
        run: cat /home/runner/.embulk/embulk.properties

      - run: ./embulk \
             -X jruby=file:///home/runner/jruby-complete-${JRUBY_VERSION}.jar \
             -X m2_repo=/home/runner/.m2/repository \
             preview ${{ matrix.config }}