name: run config

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: "zulu"

      - run: curl -o ./embulk -L https://github.com/embulk/embulk/releases/download/v${EMBULK_VERSION}/embulk-${EMBULK_VERSION}.jar
        env:
          EMBULK_VERSION: 0.11.0

      - run: chmod +x ./embulk

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'settings.gradle.kts', 'build.gradle.kts', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: ./gradlew dependencies

      - run: ./gradlew publishToMavenLocal

      - run: cp build/publications/embulkPluginMaven/pom-default.xml pom.xml

      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - run: mvn install

      - run: ./gradlew generateEmbulkProperties

      - run: sed config.yml.template -e "s/AHREFS_API_KEY/${{ secrets.AHREFS_API_KEY }}/g" > config.yml

      - run: ./embulk run config.yml